const emailRegex = /^\S+@\S+\.\S+$/

// const MAX_SCREEN_WIDTH = 1280;
// const MEDIUM_SCREEN_WIDTH = 768;
// const SMALL_SCREEN_WIDTH = 500;

// const INIT_MAX_SCREEN = 12;
// const INIT_MEDIUM_SCREEN = 8;
// const INIT_SMALL_SCREEN = 5;

// const STEP_MAX_SCREEN = 3;
// const STEP_MEDIUM_SCREEN = 2;
// const STEP_SMALL_SCREEN = 2;

const MAX_SCREEN_WIDTH = 1267;
const MEDIUM_SCREEN_WIDTH = 1267;
const SMALL_SCREEN_WIDTH = 750;

const INIT_MAX_SCREEN = 12;
const INIT_MEDIUM_SCREEN = 8;
const INIT_SMALL_SCREEN = 5;

const STEP_MAX_SCREEN = 3;
const STEP_MEDIUM_SCREEN = 2;
const STEP_SMALL_SCREEN = 2;

export {
    emailRegex,

    MAX_SCREEN_WIDTH,
    MEDIUM_SCREEN_WIDTH,
    SMALL_SCREEN_WIDTH,

    INIT_MAX_SCREEN,
    INIT_MEDIUM_SCREEN,
    INIT_SMALL_SCREEN,

    STEP_MAX_SCREEN,
    STEP_MEDIUM_SCREEN,
    STEP_SMALL_SCREEN
}